### ISSUE TITLE
BACKEND: Add an Alias Table/API to Keep the Different Versions for a Tag

### ISSUE THREAD

**Issue by emecas** [civictechindex/CTI-website-backend#31]
Samples:  

- `hack-for-la` ,  `hackforla` ,  `hack4la`,  `hack-4-la`
- `code-for-america`  ,  `codeforamerica`  ,  `code-4-america` ,  `code4america `
-  `civictechindex` ,  `civic-tech-index`

**Comment by emecas** [comment]
![image](https://user-images.githubusercontent.com/849502/105941790-33463a00-602c-11eb-8cd0-3613963109bd.png)

**Comment by emecas** [comment]
Progress Report 02/07/2021: 
 
Created PR #36 available for review.  ( @cnk @giosce @shinjonathan )

**Comment by Olivia-Chiong** [comment]
@cnk and @giosce please review and commit if OK

**Comment by giosce** [comment]
I'm still not clear of the use cases to have the alias API (including post and patch endpoints).
