### ISSUE TITLE
BACKEND: Documenting how to add a new API/Model (using alias sample)

### ISSUE THREAD

**Issue by emecas** [civictechindex/CTI-website-backend#35]
Based on the experience adding `Alias` API/Model to the backend provide a step-by-step summary.

To Do:
 - [x] Add a draft of the howto to this issue
 - [x] Define where to locate it
 - Review Completed:
    - [x] @Olivia-Chiong  
    - [x] @cnk 
    - [x] @giosce  
 - [x] Add to back-end WIKI

**Comment by emecas** [comment]
### Draft

Django Notes Adding Alias API

1. Adding Model `Alias` under: `civictechindexadmin/data/models.py`

```
# ###### Alias ###########
class Alias(models.Model):
    tag = models.CharField(max_length=30)
    alias = models.CharField(max_length=30)

    def __str__(self):
        return f"Alias {self.id}: {self.tag} {self.alias}"
```

2. Adding admin class `AliasAdmin` under `civictechindexadmin/data/admin.py`

2.1. Importing the model class

`from .models import Organization, Link, FAQ, NotificationSubscription, Alias`

2.2. Definig admin class

```
class AliasAdmin(admin.ModelAdmin):
    model = Alias
    list_display = ('id', 'tag', 'alias')
    list_filter = ('tag', 'alias',)
    search_fields = ('tag', 'alias')
```

2.3. Registering admin class

`admin.site.register(Alias, AliasAdmin)`



3. Adding Serializer   `AliasSerializer` under: `civictechindexadmin/data/api/serializers.py`
 
3.1. Importing the model class

`from ..models import Organization, Link, FAQ, NotificationSubscription, Alias`

3.2. Defining serializer class

```
class AliasSerializer(serializers.ModelSerializer):
    class Meta:
        model = Alias
        fields = ['id', 'tag', 'alias', ]
        depth = 1
```

4. Adding View `AliasViewSet` under: `civictechindexadmin/data/api/views.py`

4.1. Importing serializer class

`from .serializers import OrganizationSerializer, LinkSerializer, FAQSerializer, NotificationSubscriptionSerializer, AliasSerializer`

4.2. Importing the model class

`from ..models import Organization, Link, FAQ, Alias`

4.3.  importing `CreateModelMixin` in order to make available POST method:

`from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin, CreateModelMixin`

4.4. Defining view class including `CreateModelMixin`

```
class AliasViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet, CreateModelMixin):
    serializer_class = AliasSerializer
    queryset = Alias.objects.all()
    lookup_field = "alias"
```

5. Adding admin class `AliasAdmin` under: `civictechindexadmin/data/admin.py`

5.1. Importing the model class

`from .models import Organization, Link, FAQ, NotificationSubscription, Alias`

5.2. Defining admin class

```
class AliasAdmin(admin.ModelAdmin):
    model = Alias
    list_display = ('id', 'tag', 'alias')
    list_filter = ('tag', 'alias',)
    search_fields = ('tag', 'alias')
```
5.3. registering admin

`admin.site.register(Alias, AliasAdmin)`

6. Registering API router at `config/api_router.py`

6.1. Importing  view:

```
from civictechindexadmin.data.api.views import (
    OrganizationViewSet, LinkViewSet, FAQViewSet, AliasViewSet,
    subscribe
)
```
6.2. registering router:

`router.register("aliases", AliasViewSet)`

7. Rebuilding container

`(base) ~/hackforla/CTI-website-backend$ docker-compose up -d --build`

8. Making migrations

`(base) ~/hackforla/CTI-website-backend$ docker-compose exec web python manage.py makemigrations`

Generated files:

```
	civictechindexadmin/contrib/sites/migrations/0004_auto_20210205_2112.py
	civictechindexadmin/data/migrations/0009_alias.py
	civictechindexadmin/users/migrations/0002_auto_20210205_2112.py
```

Content of civictechindexadmin/data/migrations/0009_alias.py:

```

# Generated by Django 3.1.5 on 2021-02-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_add_link_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
            ],
        ),
    ]
```

**Comment by emecas** [comment]
Progress Report 02/07/2021:

This is available for review. 

could this be a useful resource for onboarding? What/where would be an ideal place to make this kind of documentation availabe? ( @ExperimentsInHonesty @Olivia-Chiong @cnk @giosce  )

**Comment by Olivia-Chiong** [comment]
@emecas let's put this in the backend and put a link in the frontend wiki

**Comment by cnk** [comment]
Please move the section about making migrations to immediately after section 1 about adding or editing models. And please add a note that you should be careful to only include migrations for the changes included in the model edits. Before running the migration, one should rename it to something descriptive. When adding a single table, the autogenerated name is usually good enough - but when the name is something like `0002_auto_20210205_2112`, it needs to be renamed.

**Comment by emecas** [comment]
> 
> 
> Please move the section about making migrations to immediately after section 1 about adding or editing models. And please add a note that you should be careful to only include migrations for the changes included in the model edits. Before running the migration, one should rename it to something descriptive. When adding a single table, the autogenerated name is usually good enough - but when the name is something like `0002_auto_20210205_2112`, it needs to be renamed.

Done, I have reordered the sections following your indications as well as added some notes in he step 2 about the migration generated files.

thanks

**Comment by Olivia-Chiong** [comment]
@emecas is discussing with @giosce regarding information to put into the Wiki

**Comment by giosce** [comment]
It looks good to me.

**Comment by cnk** [comment]
One more item. I think section 5 should have a link to the DRF docs on ViewSets. Not all our serializers need all items in the list you gave in your example. In fact, do we want to write to the Alias table from the front end? if not, this should probably have a ReadOnlyModelViewset - https://www.django-rest-framework.org/api-guide/viewsets/#readonlymodelviewset 

But even without this edit, I think this is a valuable addition to the project wiki.

**Comment by emecas** [comment]
> 
> 
> One more item. I think section 5 should have a link to the DRF docs on ViewSets. Not all our serializers need all items in the list you gave in your example. In fact, do we want to write to the Alias table from the front end? if not, this should probably have a ReadOnlyModelViewset - https://www.django-rest-framework.org/api-guide/viewsets/#readonlymodelviewset
>

Thank you @cnk,  I have added a note at the end of section 5.
 
> But even without this edit, I think this is a valuable addition to the project wiki.

If there is not any additional feedback, I will move this to the wiki.

**Comment by emecas** [comment]
New wiki page is available here:
https://github.com/civictechindex/CTI-website-backend/wiki/How-to-Add-a-New-API-Model-Base-on-Alias-Sample
